Allow setting -remote option
Issue #2
Fixed typo in config checks, now it prevents traceroute and
remote from being set simultaneously as expected.

Test:
netmon -test -remote="8.8.8.8"
netmon -test -traceroute="1.1.1.1" -remote="8.8.8.8"
Error: select either traceroute OR remote